#!/bin/sh

structure $project
  window editor
    vsplit
      pane right
        run "conda activate uw_py220_extras && vim"
      pane left
        hsplit
          run "conda activate uw_py220_extras && git status"
      pane down
          run "conda activate uw_py220_extras && python"

focus editor
connect $project
