# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker"
  config.vm.box = "tknerr/baseimage-ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 7474, host: 7474
  config.vm.network "forwarded_port", guest: 7473, host: 7473
  config.vm.network "forwarded_port", guest: 7687, host: 7687
  config.vm.provision "shell", inline: <<-SHELL
     export DEBIAN_FRONTEND=noninteractive
     apt-get update
     apt-get install -y dialog apt-utils
     apt-get install -y gnupg
     apt-get install -y wget
     wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
     echo 'deb https://debian.neo4j.com stable latest' | sudo tee /etc/apt/sources.list.d/neo4j.list
     echo "deb http://httpredir.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list.d/stretch-backports.list
     sudo add-apt-repository -y ppa:openjdk-r/ppa
     sudo apt-get update
     apt-get install -y neo4j
     sudo mkdir -p /data/db
     # run with vagrant ssh -- -t 'sudo  &'
  SHELL
end
